sudo: required

services:
  - docker

before_install:
  - docker pull commonsearch/local-elasticsearch
  - docker run -d -p 39200:9200 -p 39300:9300 commonsearch/local-elasticsearch
  - docker pull commonsearch/local-back
  - docker ps
  - docker info
  - docker version
  - ps -ef
  - netstat -lpn
  - docker run commonsearch/local-back ip route show 0.0.0.0/0
  - docker run commonsearch/local-back cat /etc/hosts
  - curl "http://127.0.0.1:39200"
  - docker run -e COSR_ELASTICSEARCHTEXT commonsearch/local-back curl $COSR_ELASTICSEARCHTEXT

script:
  - make docker_pylint
  - make docker_test_coverage

after_success:
  - coveralls